@extends('index')
@section('content')
    @include('components.navbar')
    @include('client.guest.sections.hero')
    @include('client.guest.sections.product-bio')
    @include('client.guest.sections.product-degra')
    @include('client.guest.sections.about')
    @include('components.footer')
@endsection
